"""Removed the aadhar card table

Revision ID: 0e645d0ca299
Revises: 8d02c13661a3
Create Date: 2021-05-24 14:58:26.637390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e645d0ca299'
down_revision = '8d02c13661a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'aadhar_card_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('aadhar_card_no', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
