"""Removed the aadhar card table

Revision ID: 4528aa8a7ff3
Revises: c32b4d9244d9
Create Date: 2021-05-25 10:45:13.191764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4528aa8a7ff3'
down_revision = 'c32b4d9244d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'aadhar_card_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('aadhar_card_no', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
