"""added the column in user table

Revision ID: 8d02c13661a3
Revises: 3ce352e7d1e1
Create Date: 2021-05-24 11:21:27.424462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d02c13661a3'
down_revision = '3ce352e7d1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('aadhar_card_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'aadhar_card_no')
    # ### end Alembic commands ###
