"""Removed the aadhar card table

Revision ID: c32b4d9244d9
Revises: 0e645d0ca299
Create Date: 2021-05-25 10:34:28.962125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32b4d9244d9'
down_revision = '0e645d0ca299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('aadhar_card_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'aadhar_card_no')
    # ### end Alembic commands ###
